### PR TITLE
"Single variable" Env Provider Type

### PR DESCRIPTION
**Pull request by tejoha**
See pull request  #77 

Added a new "env provider type" to set a single environment variable by a selected option. Sample implementation: "IP".

EnvFilejpg

### CODE REVIEW

**Comment by ashald** [comment]
Thank you for the contribution! I will try my best to find time to review it as soon as possible.

**Comment by ashald** [comment]
Just a heads up: my laptop is been stuck in Apple repair chain and my OSS activity is suspended until it’s back.
I appreciate the contribution and eager to get it merged!

**Comment by ashald** [comment]
I'm super sorry for a late reply - don't have much spare time to maintain the plugin so it took me a while to get back to this. 

First of all, thank you again for spending your time on contributing to the plugin.

Could you please take a look at this comment https://github.com/ashald/EnvFile/pull/92#issuecomment-606350489 - do you think using same approach could address your use-case? As mentioned in by the link, I believe that the less code is better and while merging this PR would've provided some convenience, given that similar functionality can be achieved by executing external tools by an IDE in an automated way, I'd rather err on the side of not merging the PR.

Please let me know what do you think about it.

**Comment by tejoha** [comment]
I tried it a little bit and found a Issue: 

1. I created a small shell script like you, but added a sleep command
```bash
sleep 5
echo "Foo=$(Date)" > src/dev.env
```


2. Created a simple Java program
```java 
public class Foo {
    public static empty main(String[] args) {
        System.out.println(System.getenv("Foo"));
    }
}
```
3. Addd the script to "Before Launch"
image


The problem is that the IDE just launches the script, but doesn't wait for it to finish. The Java program (and the EnvFile plugin) is executed before the script has finished. So the EnvFile plugin cannot read the current version file.
I think this is also the reason for the PR https://github.com/ashald/EnvFile/pull/92

**Comment by ashald** [comment]
Great catch, thanks! I will keep looking into it.

**Comment by ashald** [comment]
It's been forever, but FWIW I now think that plugin should evolve to support more sources.
I'm not sure about "single-value" though, and rather think about allowing plugin to run scripts so that you can could generate whatever env vars you want to output them via stdout. This way, you could make network calls, run system utils [to get the IP address], etc. With that in mind I'll be rejecting this PR, but keep an eye on the plugin updates for new functionality.

**Pull request closed without merging**
