### PR TITLE
Need help with goland support

### PR DESCRIPTION
**Pull request by Kelnor277**
I think I this should work? Unless there's some special cases for go run configs. However, I can't seem to figure out how to build it, in order to test. Any help in how to build the plugin for local testing would be appreciated.

Thanks.

### CODE REVIEW

**Comment by Kelnor277** [comment]
Just saw the migrate to gradle PR. That might help me.

**Comment by ashald** [comment]
Thanks for the contribution! I can confirm that it works - great job. Given that #68 was merged I will go ahead and merge this PR so I can move forward with the release.

**Comment by Kelnor277** [comment]
Nice, must be the first time I ever wrote code that worked on the first try... and by wrote I mean copied your other code and changed the class name to the go run config.

**Comment by ashald** [comment]
There were few mismatches in configuration [but it's always super tricky to figure them out for IDEA - I struggle with it all the time], but code was fine. 👍 
And I do love copy-pasting existing code and adjusting it as needed as well. 😉

**Pull request merged**
